networks:
  arrnet:
    driver: bridge
    external: true

services:       

  # ██████╗ ██████╗  ██████╗ ██╗    ██╗██╗      █████╗ ██████╗ ██████╗ 
  # ██╔══██╗██╔══██╗██╔═══██╗██║    ██║██║     ██╔══██╗██╔══██╗██╔══██╗
  # ██████╔╝██████╔╝██║   ██║██║ █╗ ██║██║     ███████║██████╔╝██████╔╝
  # ██╔═══╝ ██╔══██╗██║   ██║██║███╗██║██║     ██╔══██║██╔══██╗██╔══██╗
  # ██║     ██║  ██║╚██████╔╝╚███╔███╔╝███████╗██║  ██║██║  ██║██║  ██║
  # ╚═╝     ╚═╝  ╚═╝ ╚═════╝  ╚══╝╚══╝ ╚══════╝╚═╝  ╚═╝╚═╝  ╚═╝╚═╝  ╚═
  
    prowlarr:
      image: linuxserver/prowlarr:latest
      container_name: prowlarr
      hostname: prowlarr
      volumes:
        - ${ARRPATH}Prowlarr/config:/config
        - ${ARRPATH}Prowlarr/backup:/data/Backup
        - ${ARRPATH}Downloads:/downloads
      ports:
        - 9696:9696
      dns:
        - 8.8.8.8
        - 1.1.1.1
      restart: unless-stopped
      env_file:
        - '.env'
      networks:
        - arrnet
        
  # ███████╗ ██████╗ ███╗   ██╗ █████╗ ██████╗ ██████╗ 
  # ██╔════╝██╔═══██╗████╗  ██║██╔══██╗██╔══██╗██╔══██╗
  # ███████╗██║   ██║██╔██╗ ██║███████║██████╔╝██████╔╝
  # ╚════██║██║   ██║██║╚██╗██║██╔══██║██╔══██╗██╔══██╗
  # ███████║╚██████╔╝██║ ╚████║██║  ██║██║  ██║██║  ██║
  # ╚══════╝ ╚═════╝ ╚═╝  ╚═══╝╚═╝  ╚═╝╚═╝  ╚═╝╚═╝  ╚═╝                                                 
  
    sonarr:
      image: linuxserver/sonarr:latest
      container_name: sonarr
      hostname: sonarr
      volumes:
        - ${ARRPATH}Sonarr/config:/config
        - ${ARRPATH}Sonarr/backup:/data/Backup
        - ${ARRPATH}Sonarr/tvshows:/data/tvshows
        - ${ARRPATH}Downloads:/downloads
      ports:
        - 8989:8989
      restart: unless-stopped
      env_file:
        - '.env'
      networks:
        - arrnet
        
    # ██████╗  █████╗ ██████╗  █████╗ ██████╗ ██████╗ 
    # ██╔══██╗██╔══██╗██╔══██╗██╔══██╗██╔══██╗██╔══██╗
    # ██████╔╝███████║██║  ██║███████║██████╔╝██████╔╝
    # ██╔══██╗██╔══██║██║  ██║██╔══██║██╔══██╗██╔══██╗
    # ██║  ██║██║  ██║██████╔╝██║  ██║██║  ██║██║  ██║
    # ╚═╝  ╚═╝╚═╝  ╚═╝╚═════╝ ╚═╝  ╚═╝╚═╝  ╚═╝╚═╝  ╚═╝                                              

    radarr:
      image: linuxserver/radarr:latest
      container_name: radarr
      hostname: radarr
      volumes:
        - ${ARRPATH}Radarr/config:/config
        - ${ARRPATH}Radarr/movies:/data/movies
        - ${ARRPATH}Radarr/backup:/data/Backup
        - ${ARRPATH}Downloads:/downloads
      ports:
        - 7878:7878
      restart: unless-stopped
      env_file:
        - '.env'
      networks:
        - arrnet

        
  # ██╗     ██╗██████╗  █████╗ ██████╗ ██████╗ 
  # ██║     ██║██╔══██╗██╔══██╗██╔══██╗██╔══██╗
  # ██║     ██║██║  ██║███████║██████╔╝██████╔╝
  # ██║     ██║██║  ██║██╔══██║██╔══██╗██╔══██╗
  # ███████╗██║██████╔╝██║  ██║██║  ██║██║  ██║
  # ╚══════╝╚═╝╚═════╝ ╚═╝  ╚═╝╚═╝  ╚═╝╚═╝  ╚═╝
  
    lidarr:
      image: linuxserver/lidarr:latest
      container_name: lidarr
      hostname: lidarr
      volumes:
        - ${ARRPATH}Lidarr/config:/config
        - ${ARRPATH}Lidarr/music:/data/musicfolder
        - ${ARRPATH}Downloads:/downloads
      ports:
        - 8686:8686
      restart: unless-stopped
      env_file:
        - '.env'
      networks:
        - arrnet

  # ██╗  ██╗ ██████╗ ███╗   ███╗ █████╗ ██████╗ ██████╗ 
  # ██║  ██║██╔═══██╗████╗ ████║██╔══██╗██╔══██╗██╔══██╗
  # ███████║██║   ██║██╔████╔██║███████║██████╔╝██████╔╝
  # ██╔══██║██║   ██║██║╚██╔╝██║██╔══██║██╔══██╗██╔══██╗
  # ██║  ██║╚██████╔╝██║ ╚═╝ ██║██║  ██║██║  ██║██║  ██║
  # ╚═╝  ╚═╝ ╚═════╝ ╚═╝     ╚═╝╚═╝  ╚═╝╚═╝  ╚═╝╚═╝  ╚═╝
  
    homarr:
      container_name: homarr
      image: ghcr.io/ajnart/homarr:latest
      restart: unless-stopped
      volumes:
        - ${ARRPATH}Homarr/configs:/app/data/configs
        - ${ARRPATH}Homarr/icons:/app/public/icons
        - ${ARRPATH}Homarr/data:/data
      ports:
        - '7575:7575'
      env_file:
        - '.env'
      networks:
        - arrnet
        
  #  ██████╗ ██████╗ ██╗████████╗████████╗ ██████╗ ██████╗ ██████╗ ███████╗███╗   ██╗████████╗
  # ██╔═══██╗██╔══██╗██║╚══██╔══╝╚══██╔══╝██╔═══██╗██╔══██╗██╔══██╗██╔════╝████╗  ██║╚══██╔══╝
  # ██║   ██║██████╔╝██║   ██║      ██║   ██║   ██║██████╔╝██████╔╝█████╗  ██╔██╗ ██║   ██║   
  # ██║▄▄ ██║██╔══██╗██║   ██║      ██║   ██║   ██║██╔══██╗██╔══██╗██╔══╝  ██║╚██╗██║   ██║   
  # ╚██████╔╝██████╔╝██║   ██║      ██║   ╚██████╔╝██║  ██║██║  ██║███████╗██║ ╚████║   ██║   
  #  ╚══▀▀═╝ ╚═════╝ ╚═╝   ╚═╝      ╚═╝    ╚═════╝ ╚═╝  ╚═╝╚═╝  ╚═╝╚══════╝╚═╝  ╚═══╝   ╚═╝                                                                                          
  
    qbittorrent:
      image: linuxserver/qbittorrent:latest
      container_name: qbittorrent
      hostname: qbittorrent
      restart: unless-stopped
      labels:
        - "com.centurylinklabs.watchtower.enable=false"
      volumes:
        - ${ARRPATH}qbittorrent/config:/config
        - ${ARRPATH}Downloads:/downloads
      ports:
        - 8080:8080
        - 6881:6881
        - 6881:6881/udp
      environment:
        - WEBUI_PORT=8080
        - TORRENTING_PORT=6881
      healthcheck:
        start_period: 15s
      env_file:
        - '.env'
      networks:
        - arrnet

    jellyseerr:
      image: fallenbagel/jellyseerr:latest
      container_name: jellyseerr
      restart: unless-stopped
      ports:
        - 5055:5055
      env_file:
        - '.env'
      volumes:
        - ${ARRPATH}jellyseerr/config:/app/config
      networks:
        - arrnet
      dns:
      - 1.1.1.1  # Cloudflare DNS
      - 8.8.8.8  # Google DNS
    
    flaresolverr:
      image: ghcr.io/flaresolverr/flaresolverr:latest
      container_name: flaresolverr
      restart: unless-stopped
      ports:
        - 8191:8191
      env_file:
        - '.env'
      networks:
        - arrnet