services:
  homer:
    image: b4bz/homer:latest
    container_name: homer
    volumes:
      - ./assets:/www/assets
    ports:
      - 3000:8080
    user: 1000:1000
    environment:
      - INIT_ASSETS=0
    restart: unless-stopped