version: '3.8'

services:
  ui:
    image: subhomoy/agno-ui:latest
    ports:
      - 3000:3000
    restart: unless-stopped
    networks:
      - agno_network

  agent:
    image: subhomoy/homelab-agno-service:latest
    environment:
      - LITELLM_BASE_URL=${LITELLM_BASE_URL}
      - LITELLM_API_KEY=${LITELLM_API_KEY}
    restart: unless-stopped
    networks:
      - agno_network

networks:
  agno_network:
    driver: bridge