http:
  routers:
    ai-agents-router:
      entryPoints:
        - websecure
      rule: Host(`ai-agents.homelab.local`)
      service: ai-agents-svc
      tls: {}
      middlewares:
        - redirect-https
        - secure-headers
        - rate-limit
        - compress

  services:
    ai-agents-svc:
      loadBalancer:
        passHostHeader: true
        servers:
          - url: "http://192.168.31.171:8000"
