http:
  routers:
    jellyfin-router:
      entryPoints:
        - websecure
      rule: Host(`jellyfin.homelab.local`)
      service: jellyfin-svc
      tls: {}
      middlewares:
        - secure-headers

  services:
    jellyfin-svc:
      loadBalancer:
        passHostHeader: true
        responseForwarding:
          flushInterval: -1
        servers:
          - url: "http://192.168.31.75:8096"
