http:
  routers:
    nextcloud-router:
      entryPoints:
        - websecure
      rule: Host(`nextcloud.homelab.local`)
      service: nextcloud-svc
      tls: {}
      middlewares:
        - secure-headers
        - rate-limit
        - compress

  services:
    nextcloud-svc:
      loadBalancer:
        passHostHeader: true
        serversTransport: insecure
        servers:
          - url: "https://192.168.31.217"
