http:
  routers:
    traefik-dashboard-router:
      entryPoints:
        - websecure
      rule: Host(`traefik.homelab.local`)
      service: traefik-dashboard-svc
      tls: {}
      middlewares:
        - redirect-https

    proxmox-router:
      entryPoints:
        - websecure
      rule: Host(`proxmox.homelab.local`)
      service: proxmox-svc
      tls: {}
      middlewares:
        - redirect-https

    adguard-router:
      entryPoints:
        - websecure
      rule: Host(`adguard.homelab.local`)
      service: adguard-svc
      tls: {}
      middlewares:
        - redirect-https
        - authelia
        - secure-headers
        - rate-limit
        - compress

    authelia-router:
      entryPoints:
        - websecure
      rule: Host(`auth.homelab.local`)
      service: authelia-svc
      tls: {}
      middlewares:
        - secure-headers
        - rate-limit
        - compress
        - redirect-https

  services:
    traefik-dashboard-svc:
      loadBalancer:
        passHostHeader: true
        servers:
          - url: "http://192.168.31.5:8080"

    proxmox-svc:
      loadBalancer:
        serversTransport: "pve"
        servers:
          - url: "https://192.168.31.249:8006"
    
    adguard-svc:
      loadBalancer:
        passHostHeader: true
        servers:
          - url: "http://192.168.31.168:80"
    
    authelia-svc:
      loadBalancer:
        passHostHeader: true
        serversTransport: "pve"
        servers:
          - url: "https://192.168.31.12:9091"

  serversTransports:
    pve:
      insecureSkipVerify: true
