apiVersion: v1
kind: Service
metadata:
  name: myapp-service
  annotations:
    tailscale.com/expose: "true"
spec:
  type: LoadBalancer
  loadBalancerClass: tailscale
  selector:
    app: myapp
  ports:
  - port: 80
    targetPort: 80
