services:
  waha:
    image: devlikeapro/waha
    restart: unless-stopped
    ports:
      - "4100:3000"
    volumes:
      - '/home/komodo_data/sessions:/app/.sessions'
    dns:
      - 1.1.1.1
      - 8.8.8.8
    env_file:
      - .env

volumes:
  waha_data: