title: "Homelab Dashboard"
subtitle: "Self-hosted Service Dashboard"
logo: "https://cdn-icons-png.freepik.com/512/3518/3518775.png?filename=hacker_3518775.png&fd=1"
header: true
footer: '<span>Made with ❤️ by <a href="https://src-portfolio.oderna.in/" target="_blank">crackedngineer</a></span> .<span> Connect on <a href="https://github.com/crackedngineer" target="_blank">GitHub</a> / <a href="https://linkedin.com/in/subhomoy-roy-choudhury" target="_blank">LinkedIn</a></span>'
links:
  - name: "GitHub"
    icon: "fab fa-github"
    url: "https://github.com/crackedngineer/homelab-infrastructure"
    target: "_blank"

services:
  - name: "Dashboards & Monitoring"
    icon: "fas fa-chart-line"
    items:
      - name: "Grafana"
        type: Ping
        method: head
        logo: "https://cdn.jsdelivr.net/gh/selfhst/icons/png/grafana.png"
        subtitle: "Monitoring and metrics"
        tag: "dashboard"
        url: "http://grafana.local.oderna.in"
        target: "_blank"

      - name: "MySpeed"
        logo: "https://cdn.jsdelivr.net/gh/selfhst/icons/png/myspeed.png"
        subtitle: "Speedtest UI"
        tag: "network"
        url: "http://myspeed.local.oderna.in"
        target: "_blank"

  - name: "Media & Utilities"
    icon: "fas fa-cogs"
    items:
      - name: "Jellyfin"
        type: "Emby"
        logo: "https://cdn.jsdelivr.net/gh/selfhst/icons/png/jellyfin.png"
        subtitle: "Media Server"
        tag: "media"
        url: "http://jellyfin.local.oderna.in"
        target: "_blank"
        apikey: "bfde5b443c4a48c1b60bede23814fabe"
        libraryType: "movies"

      - name: "Stirling PDF"
        logo: "https://cdn.jsdelivr.net/gh/selfhst/icons/png/stirling-pdf.png"
        subtitle: "PDF Toolkit"
        tag: "utility"
        url: "http://stirling-pdf.local.oderna.in"
        target: "_blank"

  - name: "Dev & Automation"
    icon: "fas fa-tools"
    items:
      - name: "n8n"
        logo: "https://cdn.jsdelivr.net/gh/selfhst/icons/png/n8n.png"
        subtitle: "Workflow Automation"
        tag: "automation"
        url: "http://n8n.local.oderna.in"
        target: "_blank"

      - name: "LiteLLM"
        logo: "https://cdn.jsdelivr.net/gh/selfhst/icons/png/litellm.png"
        subtitle: "OpenAI-compatible Gateway"
        tag: "LLM"
        url: "http://litellm.local.oderna.in"
        target: "_blank"

      - name: "IT Tools"
        logo: "https://cdn.jsdelivr.net/gh/selfhst/icons/webp/it-tools.webp"
        subtitle: "Network & Dev Tools"
        tag: "dev"
        url: "http://ittools.local.oderna.in"
        target: "_blank"

      - name: "OmniTools"
        logo: "https://cdn.jsdelivr.net/gh/selfhst/icons/png/omnitools.png"
        subtitle: "Multi-tool Dev Dashboard"
        tag: "tools"
        url: "http://omnitools.local.oderna.in"
        target: "_blank"

  - name: "System & Infra"
    icon: "fas fa-network-wired"
    items:
      - name: "Proxmox - Node"
        logo: "https://cdn.jsdelivr.net/gh/selfhst/icons/png/proxmox.png"
        url: "https://100.81.69.28:8006/"
        target: "_blank"

        # type: "Proxmox"
        # node: "pve"
        # warning_value: 50
        # danger_value: 80
        # api_token: "PVEAPIToken=root@pam!homer=234251f4-5807-46ed-aef8-c368d360120f"
        # # values below this line are optional (default value are false/empty):
        # hide_decimals: true # removes decimals from stats values.
        # hide: ["vms", "vms_total", "lxcs", "lxcs_total", "disk", "mem", "cpu"] # hides information. Possible values are "vms", "vms_total", "lxcs", "lxcs_total", "disk", "mem" and "cpu".
        # small_font_on_small_screens: true # uses small font on small screens (like mobile)
        # small_font_on_desktop: true

      - name: "Home Assistant"
        type: "HomeAssistant"
        logo: "https://cdn.jsdelivr.net/gh/selfhst/icons/png/home-assistant.png"
        subtitle: "Smart Home Control"
        apikey: "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiIyNjM5MTI1YzY0OTA0NjNkYmY5Nzc1ZTg2MDMyZjMwNCIsImlhdCI6MTc1MjkyMDQ0NywiZXhwIjoyMDY4MjgwNDQ3fQ.4eBaUh4AHzO-TQW4H2cWzRM9f2zK_XSqtXyAlGTH5zs"
        tag: "infra"
        url: "http://homeassistant.local.oderna.in"
        target: "_blank"
        items: []
        seperator: " | "

      - name: "Komodo"
        logo: "https://cdn.jsdelivr.net/gh/selfhst/icons/png/komodo.png"
        subtitle: "Container Platform"
        tag: "infra"
        url: "http://komodo.local.oderna.in"
        target: "_blank"

      - name: "NPM"
        logo: "https://cdn.jsdelivr.net/gh/selfhst/icons/png/nginx-proxy-manager.png"
        subtitle: "Nginx Proxy Manager"
        tag: "infra"
        url: "http://npm.local.oderna.in"
        target: "_blank"

      - name: "OpenWebUI"
        logo: "https://cdn.jsdelivr.net/gh/selfhst/icons/png/open-webui.png"
        subtitle: "LLM Chat UI"
        tag: "infra"
        url: "http://openwebui.local.oderna.in"
        target: "_blank"

      - name: "PiHole"
        logo: "https://cdn.jsdelivr.net/gh/selfhst/icons/png/pi-hole.png"
        subtitle: "Ad Blocker DNS"
        tag: "dns"
        url: "http://pihole.local.oderna.in/admin/"
        target: "_blank"

        # endpoint: "http://192.168.0.151" # optional, For v6 API, this is the base URL used to fetch Pi-hole data overwriting the url
        # apikey: "<---insert-api-key-here--->" # optional, needed if web interface is password protected
        # type: "PiHole"
        # apiVersion: 6 # optional, defaults to 5. Use 6 if your PiHole instance uses API v6
        # checkInterval: 3000 # optional, defaults to 300000. interval in ms to check Pi-hole status

      - name: "Agno Agent"
        logo: "assets/icons/agno.png"
        subtitle: "Custom Agent UI"
        tag: "agent"
        url: "http://agno-agent.local.oderna.in/ui/"
        target: "_blank"
