---
- name: Deploy Agno UI app in Proxmox LXC container
  hosts: agno_ui
  become: true

  vars:
    app_dir: /opt/app
    repo_url: "https://github.com/crackedngineer/agno-assistant.git"

  tasks:
    - name: Overwrite resolv.conf with Google DNS
      copy:
        content: |
          nameserver 8.8.8.8
          nameserver 1.1.1.1
        dest: /etc/resolv.conf
        force: yes

    - name: Check if systemd-resolved is available
      ansible.builtin.service_facts:

    - name: Restart systemd-resolved if available
      ansible.builtin.service:
        name: systemd-resolved
        state: restarted
      when: "'systemd-resolved.service' in ansible_facts.services"

    - name: Restart networking if available
      ansible.builtin.service:
        name: networking
        state: restarted
      when: "'networking.service' in ansible_facts.services"

    - name: Install required apt packages
      ansible.builtin.apt:
        pkg:
          - curl
          - git
          - build-essential
          - openssh-server
        state: present
        update_cache: true

    - name: Install Node.js 18.x (LTS)
      shell: |
        curl -fsSL https://deb.nodesource.com/setup_18.x | bash -
        apt-get install -y nodejs
      args:
        executable: /bin/bash

    - name: Install pm2 globally
      community.general.npm:
        name: pm2
        global: true

    - name: Clone the Next.js application
      ansible.builtin.git:
        repo: "{{ repo_url }}"
        dest: "{{ app_dir }}"

    - name: Install app dependencies
      ansible.builtin.shell: npm install
      args:
        chdir: "{{ app_dir }}"

    - name: Build the Next.js app
      ansible.builtin.shell: npm run build
      args:
        chdir: "{{ app_dir }}"

    - name: Start the app using pm2
      ansible.builtin.shell: |
        pm2 start npm --name "agno-assistant" -- start
        pm2 startup systemd -u root --hp /root
        pm2 save
      args:
        chdir: "{{ app_dir }}"
