http:
  routers:
    proxmox-router:
      entryPoints:
        - websecure
      rule: Host(`proxmox.homelab`)
      service: proxmox-svc
      tls: {}

  services:
    proxmox-svc:
      loadBalancer:
        serversTransport: "pve"
        servers:
          - url: "https://192.168.31.249:8006"

  serversTransports:
    pve:
      insecureSkipVerify: true
