name: Deploy Hugo site to GitHub Pages

on:
    push:
        branches:
            - main  # Set a branch to deploy on push
    pull_request:
        branches:
            - main  # Set a branch to deploy on PR

jobs:
    build-and-deploy:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v4
              with:
                submodules: true  # Fetch Hugo themes (true OR recursive)
                fetch-depth: 0    # Fetch all history for .GitInfo and .Lastmod

            - name: Setup Hugo
              uses: peaceiris/actions-hugo@v3
              with:
                hugo-version: 'latest'
                extended: true

            - name: Build
              run: hugo --minify

            - name: Deploy to GitHub Pages
              uses: peaceiris/actions-gh-pages@v4
              if: github.ref == 'refs/heads/main'
              with:
                github_token: ${{ secrets.GH_TOKEN }}
                publish_dir: ./public